FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir aiohttp redis
RUN pip install --no-cache-dir aiohttp sgp4 numpy
# CMD ["python", "-m", "controller.controller"]
# CMD ["python", "controller.py"]
ENV PYTHONUNBUFFERED=1
CMD ["python", "-u", "controller.py"]